apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-ip-overlap-killer
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-ip-overlap-killer
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-ip-overlap-killer
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-ip-overlap-killer
subjects:
- kind: ServiceAccount
  name: pod-ip-overlap-killer
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-ip-overlap-killer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-ip-overlap-killer
  template:
    metadata:
      labels:
        app: pod-ip-overlap-killer
    spec:
      serviceAccountName: pod-ip-overlap-killer
      containers:
      - image: slofurno/pod-cidr-overlap-killer
        name: overlap
        env:
          - name: DELETE_PODS
            value: "1"
          - name: INTERVAL_SECONDS
            value: "10"
